import com.test.client.Client;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public static void main(String... args) {
        final Client c = new Client();
        c.print();
    }
}
